import sampleCircuitPage from "../../assets/problem-sources/autocircuits/sample-page-1.png";
import { createAutoCircuitsAnswerSlots } from "./autocircuits-pdf";
import type { ProblemDocument, SourcePrefOption } from "./types";

export const autoCircuitsPartOptions: SourcePrefOption[] = [
  { value: "DC_Random", label: "DC Circuits" },
  { value: "AC_Random", label: "AC Circuits" },
  { value: "Transients", label: "Transients" },
  { value: "S_domain", label: "Frequency Responses" },
  { value: "Formulations", label: "Matrix Formulations" },
  { value: "TwoPort", label: "Two-Ports" },
];

export const autoCircuitsChapterOptions: SourcePrefOption[] = [
  { value: "Kirchhoff_Laws", label: "Kirchhoff Laws" },
  { value: "DC_Req", label: "DC Equivalent Resistance" },
  { value: "DC_Analysis", label: "DC Circuits" },
  { value: "DC_Thev_Norton", label: "DC Thevenin-Norton equivalents" },
  { value: "DC_MNA", label: "DC Modified Nodal Analysis" },
  { value: "DC_TwoPort", label: "DC Two-Ports" },
  { value: "AC_Zeq", label: "AC Equivalent Impedance" },
  { value: "AC_Analysis", label: "AC Circuits" },
  { value: "AC_Thev_Norton", label: "AC Thevenin-Norton equivalents" },
  { value: "AC_Power", label: "AC Power" },
  { value: "AC_Multifreq", label: "AC Multi-frequency" },
  { value: "I_order_DC_sources_switches", label: "First-Order circuits" },
  { value: "LTI_H_s", label: "Transfer functions" },
  { value: "LTI_H_s_h_t", label: "Impulse Responses" },
  { value: "LTI_NaturalFrequencies", label: "Natural Frequencies" },
  { value: "LTI_Bode", label: "Bode Diagrams" },
  { value: "LTI_StateEquations", label: "State Equations" },
  { value: "LTI_Transient_noIC", label: "Transients, no IC" },
  { value: "LTI_Transient_ICfromDC", label: "Transients, IC from DC Analysis" },
  { value: "LTI_Transient", label: "General Transients" },
  { value: "LTI_MNA", label: "MNA of LTI Circuits" },
  { value: "LTI_TwoPort", label: "LTI Two-Ports" },
];

export const autoCircuitsDifficultyOptions: SourcePrefOption[] = [
  { value: "eeasy", label: "Basic" },
  { value: "easy", label: "Easy" },
  { value: "medium", label: "Medium" },
  { value: "hard", label: "Hard" },
  { value: "hhard", label: "Insane" },
];

export const autoCircuitsNumberTypeOptions: SourcePrefOption[] = [
  { value: "integer", label: "Integer" },
  { value: "rational", label: "Rational" },
  { value: "real", label: "Real" },
];

export const autoCircuitsModeOptions: SourcePrefOption[] = [
  { value: "parts", label: "Parts" },
  { value: "chapters", label: "Chapters" },
  { value: "shuffle", label: "Shuffle" },
];

export const createAutoCircuitsFixtureDocument = (metadata?: ProblemDocument["source"]["metadata"]): ProblemDocument => {
  const answerSlots = createAutoCircuitsAnswerSlots([
    { id: "i2", expected: "5 A" },
    { id: "i5", expected: "-2 A" },
    { id: "i6", expected: "4 A" },
  ]);

  return {
    id: "autocircuits-sample-current-branches",
    title: "Solve the circuit",
    description: "Answer correctly to continue.",
    prompt: "Find i2, i5, and i6 for the circuit shown.",
    assets: [
      {
        id: "circuit-page",
        title: "Circuit problem",
        caption: "Rendered from a generated AutoCircuits PDF sample.",
        image: sampleCircuitPage,
      },
    ],
    answerSlots,
    footer:
      "Generated by autoCircuits.org. Licensed under Creative Commons Attribution-NonCommercial 4.0 International.",
    source: {
      id: "autocircuits-offline",
      label: "AutoCircuits Offline",
      generatedAt: "2026-06-25",
      metadata,
    },
  };
};
